title: Lavanya Jose

description: I am a computer scientist and engineer interested in distributed systems, networking and cloud computing. I am excited about developing large-scale, simple, and practical systems, which are grounded in theory. I finished my Ph.D. at Stanford, where I was advised by % [Nick McKeown]() %.

theme: jekyll-theme-tactile
